RUN_MODE = ROM

OPT = -Os

MMCULIB_DIR = ../../mmculib

DRIVERS = tcm8230 pacer led usb_cdc bbi2c

TARGET = cam.bin

SRC = cam.c

include ../../boards/sam7hxxx-tcm8230/board.mk
include $(MMCULIB_DIR)/mmculib.mk


